services:
  app:
    build: .
    ports:
      - "4000:8000"
    volumes:
      - ./app:/app
    environment:
      - PYTHONPATH=/app
    depends_on:
      qdrant:
        condition: service_started
      mongodb:
        condition: service_healthy
    networks:
      - rag-app

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - mongodb_data:/data/db
    networks:
      - rag-app

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - ./mongo-express:/usr/src/app
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
    networks:
      - rag-app

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage:z
    networks:
      - rag-app

volumes:
  mongodb_data:
    driver: local

  qdrant_storage:
    driver: local

networks:
  rag-app:
    driver: bridge
